import mongoose from "mongoose";

const universalChatMessageSchema = new mongoose.Schema(
  {
    session: {
      type: mongoose.Schema.ObjectId,
      ref: "UniversalChatSession",
      required: [true, "Message must belong to a session"],
    },
    user: {
      type: mongoose.Schema.ObjectId,
      ref: "User",
      required: [true, "Message must belong to a user"],
    },
    queryText: {
      type: String,
      trim: true,
    },
    mediaUrls: {
      image: { type: String, default: null }, // from cloudinary
      audio: { type: String, default: null }, // from cloudinary
    },
    language: {
      type: String,
      default: "en",
    },
    aiResponse: {
      type: String,
    },
    diseaseDetected: {
      type: String, // Or topic user asked about
    },
    ttsFriendly: {
      type: String, // Output generated by Konkan AI for TTS
    },
  },
  {
    timestamps: true,
  }
);

const UniversalChatMessage = mongoose.model("UniversalChatMessage", universalChatMessageSchema);

export default UniversalChatMessage;
